### ISSUE TITLE
Main travel times algorithm

### ISSUE THREAD

**Issue by mpadge** [UrbanAnalyst/m4ra#6]
## TODO:

- [x] Generate matrix of traveltimes within GTFS feed (#5)
- [x] Generate matrix of traveltimes from all network points to GTFS stops
- [x] Generate matrix of traveltimes from all GTFS stops to all network points
- [x] Algorithm to combine these three matrices
