### ISSUE TITLE
Automobile times

### ISSUE THREAD

**Issue by mpadge** [UrbanAnalyst/m4ra#9]
Automobile times are needed to convert multi-modal times to ratios relative to equivalent automobile times. Calibration of actual times has been done via https://github.com/UrbanAnalyst/ttcalib, including potential to easily calibrate times during peak hours and not. The only remaining thing is then:

- [x] Implement time penalty for car parking, including metrics of local densities of car parks.

**Comment by mpadge** [comment]
Metric is cube root of total volume of nearby buildings divided by number of car parking spaces.

## TODO

- [ ] Include car parks from OSM ways tagged with [`parking:lane:side`](https://wiki.openstreetmap.org/wiki/Key:parking:lane#Parking_spaces).
- [x] Expose both `dlim` and `k` parameters used in aggregation (currently hard-coded)

**Comment by mpadge** [comment]
The above commit adds data from on-street parking, and so yields the final estimates of the parking metric, which then looks like this:

![image](https://user-images.githubusercontent.com/6697851/202199979-8fe39cf3-6d6b-4c6c-80f7-d44ada96900e.png)

That's Mannheim and Heidelberg, where the index goes up to around 4.8. The same thing for Münster extends to a max of 3.2. That suggests a good rule-of-thumb would be either 2 or 3 minutes per unit of the index scale. A value of 2 seems possibly unrealistically low, as the maximum time to park a car and walk to desintation in Münster would then be 6 minutes. A value of 3 seems more realistic, and will now be used to finish and close this issue.

## Final scale

- Car arrival at destination = 3 times the index ratio at that point.
- Car departure = 2 times the index ratio at that point.

For Münster, that gives mean values of 3 and 4.5 minutes, and for Mannheim 3.3 and 4.9 minutes. Seems realistic.

**Comment by mpadge** [comment]
That last commit hard-codes the final multiples described above of 2 for start times and 3 for end times.
